# Generated by Django 4.2 on 2024-04-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedmeeting',
            name='calendar',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_meetings', to='scheduling.calendar'),
            preserve_default=False,
        ),
    ]
