# Generated by Django 4.2 on 2024-03-13 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='meetings',
            field=models.ManyToManyField(blank=True, to='scheduling.meetings'),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_calendars', to=settings.AUTH_USER_MODEL),
        ),
    ]
